language: cpp

dist: bionic
addons:
  apt:
    packages:
    - premake4

script:
- cd bootil/projects && premake4 gmake
- cd linux/gmake && make -j4
- cd ../../../../gmad && premake4 --bootil_lib="../bootil/lib/linux/gmake/" --bootil_inc="../bootil/include" gmake
- make -j4
- "./gmad_linux --help > /dev/null"

deploy:
  provider: releases
  api_key:
    secure: A7A+Xse6dJNpVTpgfIve3ROV/a7qmk4TSKWtp5zCWGN/wuDFczgAD6++hfC1kULKSJXLM9gQ3oebxf+mIlNi7fK++NTPeHi5IJ+dcKGiMwQC+XhSUiRixtgl71vu/unmaVK8gUf/eQ9UKPiE7Btq0yGLhZF5rNaL8m99lkm5aULhjis1M8AHCWEoH8ydN4cmI2yjYSV/xyj/o58sBypem+Ld/5jSl/tgpUWqbbWearCx/VBP5KuGx23qm+4OmBiCB9F1106nsRV2QGS4v1MbThII0nNZSq/Rb5dOYkgr2SPIUttPw2m54TlRp8bgkcFCxil8WoeTD4UUKMUYM3I2tsJO+ZIBcr4cUfJlNIX6FwzudZXFiUUe2L/CxqVHxkVPmNZZDHDC2pIxR7Rm9cNucjel+/4eImikMsUFOF1Y7RyLRinRxQmpGPwcsuNDisl4GEIBuzl4/MUFuiQUJ2yoxRlpYUn9lgtCU9W0SJ/VcNWVumrmkfNqi/ME9Ru2pbAQzGFioC1kuwssE9WDDsoosjm/EarGxbi8YD3ilcMBpnxuZHYs/MIetQrSlDhizuDbNguKA7i9mtSKHKH+UEiYJfLLKCwh6i2FIoOG87TJKR/bQxmY1hrvC59WZlw9PSwL1Z9k691lIU85KofXLzPYvNSVNz7lRJo+KV/3xByOcyg=
  file: 'gmad_linux'
  on:
    repo: wiremod/gmad-build
    tags: true
  skip_cleanup: true
